version: "3.2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      cluster.name: workflow.elasticsearch
      ES_JAVA_OPTS: -Xms2g -Xmx2g
    volumes:
      - "/data/es-config:/usr/share/elasticsearch/config"
      - "/data/es-data:/usr/share/elasticsearch/data"
      - "/data/es-logs:/usr/share/elasticsearch/logs"
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '10'
    healthcheck:
      test: 'curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s || exit 1'
      interval: 1m30s
      timeout: 50s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    ports:
      - 5601:5601
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '10'
    depends_on:
      - elasticsearch
    environment:
      LOGGING_QUIET: 'true'
      ELASTICSEARCH_USERNAME: '$ES_USERNAME'
      ELASTICSEARCH_PASSWORD: '$ES_PASSWORD'

  arranger-server:
    build:
      context: ./
      target: server
      dockerfile: Dockerfile
    container_name: arranger-server.local
    depends_on:
      - elasticsearch
    ports:
      - 5050:5050
    environment:
      ES_HOST: http://elasticsearch:9200
      ES_USER: "$ES_USERNAME"
      ES_PASS: "$ES_PASSWORD"

  arranger-ui:
    build:
      context: ./
      target: ui
      dockerfile: Dockerfile
    hostname: arranger-ui.local
    container_name: arranger-ui.local
    depends_on:
      - arranger-server
    environment:
      REACT_APP_ARRANGER_ADMIN_ROOT: "http://arranger-server:5050"
      PORT: 3000
    ports:
      - 8080:3000
  portal:
    build:
      context: ./iPC_Data_Portal
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./iPC_Data_Portal/:/app/"
